# Create a stacked bar plot
plt.figure(figsize=(10, 6))
plt.bar(advisor_skills_grouped['advisor_skill'], advisor_skills_grouped['predicted_promoters'], label='Predicted Promoters')
plt.bar(advisor_skills_grouped['advisor_skill'], advisor_skills_grouped['actual_promoters'], bottom=advisor_skills_grouped['predicted_promoters'], label='Actual Promoters')
plt.xlabel('Advisor Skill')
plt.ylabel('Count')
plt.title('Predicted vs Actual Promoters by Advisor Skill')
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.show()
